name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Restore and save dependency cache
        uses: coursier/cache-action@v6

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Compile build
        run: sbt compile
